// backend/config/constants.js
const { PublicKey } = require('@solana/web3.js');

// تأكد من صحة هذه المفاتيح!
const TREASURY_PUBLIC_KEY_STRING = "C3uyWqqRZ8brjHTPZYacxrHfvZYNQjUnza3a9Kui7R2r";
const FINAL_STORAGE_PUBLIC_KEY_STRING = "6Azd4Fyc5jqbQQRLiNRHfnECjCRcgd6yPr1uXk56NK5s";
const PROGRAM_ID_STRING = '8RzqAPhqTcGd48DxErKV3PNsvZA7ogxXGwbar6oPhPnW';
const ADMIN_AUTHORITY_STRING = "2UrhEmCmL7BUheGdECDePZFB24mPbipqYXk2wPqbXa6f"; // لسلطة توزيع المكافآت

const TOKEN_PROGRAM_ID = new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');
const SYSTEM_PROGRAM_ID = new PublicKey('11111111111111111111111111111111');

// النسب المالية
const RENT_PER_EMPTY_ATA_LAMPORTS = 2039280;
const PLATFORM_FEE_PERCENT_CONTRACT = 25; // 25%
const REFERRAL_COMMISSION_PERCENT_CONTRACT = 25; // 25% of platform fee
const TOP_REFERRER_REWARD_PERCENT = 1; // 1% of platform earnings
const TOP_CLOSER_REWARD_PERCENT = 1; // 1% of platform earnings
const FINAL_STORAGE_TRANSFER_PERCENT = 99; // 99% of net treasury profit

// أخرى
const MIN_REFERRAL_WITHDRAW_SOL = 0.05;
const LAMPORTS_PER_SOL = 1000000000;
const DEFAULT_TX_FEE_LAMPORTS = 5000;
const TARGET_HOT_WALLET_BALANCE_SOL = 2; // مثال لتمويل المحفظة الساخنة

module.exports = {
    TREASURY_PUBLIC_KEY_STRING,
    FINAL_STORAGE_PUBLIC_KEY_STRING,
    PROGRAM_ID_STRING,
    ADMIN_AUTHORITY_STRING,
    TOKEN_PROGRAM_ID,
    SYSTEM_PROGRAM_ID,
    RENT_PER_EMPTY_ATA_LAMPORTS,
    PLATFORM_FEE_PERCENT_CONTRACT,
    REFERRAL_COMMISSION_PERCENT_CONTRACT,
    TOP_REFERRER_REWARD_PERCENT,
    TOP_CLOSER_REWARD_PERCENT,
    FINAL_STORAGE_TRANSFER_PERCENT,
    MIN_REFERRAL_WITHDRAW_SOL,
    LAMPORTS_PER_SOL,
    DEFAULT_TX_FEE_LAMPORTS,
    TARGET_HOT_WALLET_BALANCE_SOL,
};