[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
ata_claim = "8RzqAPhqTcGd48DxErKV3PNsvZA7ogxXGwbar6oPhPnW"



[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
commitment = "confirmed"
rpc_timeout = 30000

[[provider.genesis]] # <-- استخدم الأقواس المزدوجة [[ ]] لتعريف عناصر في مصفوفة
address = "FcjMowCRg8NxWriMqiuxAWG1yGXuX2Vg1wHFPeQJkdBm"
filename = "test-wallet-account.json"

[[provider.genesis]]
address = "2UrhEmCmL7BUheGdECDePZFB24mPbipqYXk2wPqbXa6f"
filename = "authority-account.json"

[workspace]
members = ["."]

[scripts]
test = "npm run test"

[test]
startup_wait = 30000 

shutdown_wait = 2000
upgradeable = false
