[package]
name = "ata_claim"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
